### ISSUE TITLE
> Could not get a token from server!

### ISSUE THREAD

**Issue by ic3cold** [CSFM93/twilio-in-browser-calls#2]
127.0.0.1 - - [13/Oct/2022 19:56:15] "GET /token HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ic3cold/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ic3cold/Downloads/twilio-in-browser-calls-main/main.py", line 47, in get_token
    {'token': access_token.to_jwt().decode(), 'identity': identity})
AttributeError: 'str' object has no attribute 'decode'

**Comment by Ehsan1997** [comment]
remove the decode function call when getting the access token.
